# FROM https://github.com/bitnami/containers/blob/main/bitnami/wordpress/docker-compose.yml
# modified to use the runner filesystem instead of a volume driver
version: '2'
services:
  mariadb:
    image: docker.io/bitnami/mariadb:10.6
    volumes:
      - 'mariadb_data:/bitnami/mariadb'
    environment:
      # ALLOW_EMPTY_PASSWORD is recommended only for development.
      - ALLOW_EMPTY_PASSWORD=yes
      - MARIADB_USER=root
      - MARIADB_DATABASE=test
  wordpress:
    image: docker.io/bitnami/wordpress:latest
    ports:
      - '80:8080'
      - '443:8443'
    volumes:
        - 'wordpress_data:/bitnami/wordpress'
        - ./nlptools:/bitnami/wordpress/wp-content/plugins/wordpress-nlp-tools
    depends_on:
      - mariadb
    environment:
      # ALLOW_EMPTY_PASSWORD is recommended only for development.
      - ALLOW_EMPTY_PASSWORD=yes
      - WORDPRESS_DATABASE_HOST=mariadb
      - WORDPRESS_DATABASE_PORT_NUMBER=3306
      - WORDPRESS_DATABASE_USER=root
      - WORDPRESS_DATABASE_NAME=test
volumes:
  mariadb_data:
    driver: local
  wordpress_data:
    driver: local
