name: NLP Tools Test Workflow
run-name: ${{ github.actor }} is running tests
on: [push]
jobs:
  tests:
    strategy:
      matrix:
        suite:
          - unit
          - wpunit
          - functional
          - acceptance
    runs-on: ubuntu-latest
    steps:
      - name: Checkout plugin
        uses: actions/checkout@v3
        with:
          path: wnlp_tools
      # -------------------------------
      # Changed files
      # -------------------------------
      - name: Check changed files
        id: skip
        run: |
          num_php_files=$(git diff ${{ github.event.pull_request.base.sha }} HEAD --name-only | grep -P "\.php" | wc -l)
          if [[ -z "$num_php_files" ]]; then
            echo "::set-output name=value::1"
          elif [[ "$num_php_files" == "0" || "$num_php_files" == "" ]]; then
            echo "::set-output name=value::1"
          else
            echo "::set-output name=value::0"
          fi
      # -------------------------------
      # Set up containers
      # -------------------------------
      - name: Setup bitnami containers
        run: |
          mkdir wordpress_data
          mv wnlp_tools/docker-compose.yml .
          docker-compose up -d
      # -------------------------------
      # Build
      # -------------------------------
      - name: Run Tests
        run: |
          docker compose exec -it wordpress bash -c "cd /bitnami/wordpress/wp-content/plugins/wordpress-nlp-tools && composer install"
      # -------------------------------
      # Run
      # -------------------------------
      - name: Run Tests
        run: |
          docker compose exec -it wordpress bash -c "cd /bitnami/wordpress/wp-content/plugins/wordpress-nlp-tools && vendor/bin/codecept run ${{ matrix.suite }}" 
